function varargout = GUIStageSequence(varargin)
% GUISTAGESEQUENCE MATLAB code for GUIStageSequence.fig
%      GUISTAGESEQUENCE, by itself, creates a new GUISTAGESEQUENCE or raises the existing
%      singleton*.
%
%      H = GUISTAGESEQUENCE returns the handle to a new GUISTAGESEQUENCE or the handle to
%      the existing singleton*.
%
%      GUISTAGESEQUENCE('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in GUISTAGESEQUENCE.M with the given input arguments.
%
%      GUISTAGESEQUENCE('Property','Value',...) creates a new GUISTAGESEQUENCE or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before GUIStageSequence_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to GUIStageSequence_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help GUIStageSequence

% Last Modified by GUIDE v2.5 30-May-2018 17:41:01

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @GUIStageSequence_OpeningFcn, ...
                   'gui_OutputFcn',  @GUIStageSequence_OutputFcn, ...
                   'gui_LayoutFcn',  @GUIStageSequence_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before GUIStageSequence is made visible.
function GUIStageSequence_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to GUIStageSequence (see VARARGIN)
set(gcf,'CloseRequestFcn',[]);

% Choose default command line output for GUIStageSequence
handles.output = varargin{1};
%% Setting to default values
reset=0;
if isempty(handles.output.Control)
    reset=1;
else
    if ~strcmpi(handles.output.Control.Type,'stagedsequence')
        reset=1;
    end
end

if reset
    handles.output.Control=struct;
    handles.output.Control(1).Type='StagedSequence';
    handles.output.Control(1).Delay=120*1000; %2 mins
    handles.output.Control(1).PulseWidth=400; %400 us
    handles.output.Control(1).Repetition=1 ; %single pulse
    handles.output.Control(1).TrigDelay=0 ; %immediate start
end

setfigtovalues(handles);


% Update handles structure
guidata(hObject, handles);

% UIWAIT makes GUIStageSequence wait for user response (see UIRESUME)
uiwait(handles.figure1);

function setfigtovalues(handles)
    for i=1:length(handles.output.Control)
        eval(sprintf('set(handles.PulseWidthEdt%d,''String'',num2str(handles.output.Control(i).PulseWidth));',i));
        eval(sprintf('set(handles.RepetitionsEdt%d,''String'',num2str(handles.output.Control(i).Repetition));',i));
        eval(sprintf('set(handles.TriggerDelay%d,''String'',num2str(handles.output.Control(i).TrigDelay));',i));
        eval(sprintf('set(handles.InterPulseEdt%d,''String'',num2str(handles.output.Control(i).Delay));',i));
    end
    showsequence(handles);
        
function setvaluestofig(handles)
    for i=1:4
        eval(sprintf('Width=str2double(get(handles.PulseWidthEdt%d,''String''));',i));
        eval(sprintf('Delay=str2double(get(handles.InterPulseEdt%d,''String''));',i));
        eval(sprintf('Reps=str2double(get(handles.RepetitionsEdt%d,''String''));',i));
        eval(sprintf('TrigDel=str2double(get(handles.TriggerDelay%d,''String''));',i));
        handles.output.Control(i).PulseWidth=Width;
        handles.output.Control(i).Repetition=Reps;
        handles.output.Control(i).TrigDelay=TrigDel;
        handles.output.Control(i).Delay=Delay;
    end
    showsequence(handles);
        
function showsequence(handles)
    n=get(handles.SelectPop,'Value');
    switch n
        case 1
            imin=1;
            imax=4;
        otherwise
            imin=n-1;
            imax=n-1;
    end
    
    Delay=zeros(1,4);
    Width=zeros(1,4);
    Reps=zeros(1,4);
    TrigDel=zeros(1,4);
    
    for i=1:length(handles.output.Control)
        Delay(i)=handles.output.Control(i).Delay/1000;
        Width(i)=handles.output.Control(i).PulseWidth/1000;
        Reps(i)=handles.output.Control(i).Repetition;
        TrigDel(i)=handles.output.Control(i).TrigDelay/1000;
    end
    
    axes(handles.axes1);
    dt=handles.output.Hardware.Delay/10^6;

    for i=imin:imax
       t=-dt;
       control=0;
       
       for j=1:Reps(i)
           t=[t (j-1)*Delay(i) (j-1)*Delay(i)+Width(i) (j-1)*Delay(i)+Width(i)+dt (j)*Delay(i)-dt];
           control=[control 1 1 0 0];
       end
       
       
       if TrigDel(i)>0
           t=[0 t+TrigDel(i)];
           control=[0 control];
       end
       
       

        
        plot(t/1000,control);
        hold on
    end
    hold off
    xlabel('time (s)')
    ylabel('control')
    
    


% --- Outputs from this function are returned to the command line.
function varargout = GUIStageSequence_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(gcf,'CloseRequestFcn','closereq');
% Get default command line output from handles structure
varargout{1} = handles.output;
close(gcf);


% --- Executes on selection change in SelectPop.
function SelectPop_Callback(hObject, eventdata, handles)
% hObject    handle to SelectPop (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
showsequence(handles);
% Hints: contents = cellstr(get(hObject,'String')) returns SelectPop contents as cell array
%        contents{get(hObject,'Value')} returns selected item from SelectPop


% --- Executes during object creation, after setting all properties.
function SelectPop_CreateFcn(hObject, eventdata, handles)
% hObject    handle to SelectPop (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in DoneBttn.
function DoneBttn_Callback(hObject, eventdata, handles)
% hObject    handle to DoneBttn (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
uiresume


function PulseWidthEdt1_Callback(hObject, eventdata, handles)
% hObject    handle to PulseWidthEdt1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of PulseWidthEdt1 as text
%        str2double(get(hObject,'String')) returns contents of PulseWidthEdt1 as a double


% --- Executes during object creation, after setting all properties.
function PulseWidthEdt1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to PulseWidthEdt1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function InterPulseEdt1_Callback(hObject, eventdata, handles)
% hObject    handle to InterPulseEdt1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of InterPulseEdt1 as text
%        str2double(get(hObject,'String')) returns contents of InterPulseEdt1 as a double


% --- Executes during object creation, after setting all properties.
function InterPulseEdt1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to InterPulseEdt1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function RepetitionsEdt1_Callback(hObject, eventdata, handles)
% hObject    handle to RepetitionsEdt1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of RepetitionsEdt1 as text
%        str2double(get(hObject,'String')) returns contents of RepetitionsEdt1 as a double


% --- Executes during object creation, after setting all properties.
function RepetitionsEdt1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to RepetitionsEdt1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function TriggerDelay1_Callback(hObject, eventdata, handles)
% hObject    handle to TriggerDelay1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of TriggerDelay1 as text
%        str2double(get(hObject,'String')) returns contents of TriggerDelay1 as a double


% --- Executes during object creation, after setting all properties.
function TriggerDelay1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to TriggerDelay1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function TriggerDelay4_Callback(hObject, eventdata, handles)
% hObject    handle to TriggerDelay4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of TriggerDelay4 as text
%        str2double(get(hObject,'String')) returns contents of TriggerDelay4 as a double


% --- Executes during object creation, after setting all properties.
function TriggerDelay4_CreateFcn(hObject, eventdata, handles)
% hObject    handle to TriggerDelay4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function RepetitionsEdt4_Callback(hObject, eventdata, handles)
% hObject    handle to RepetitionsEdt4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of RepetitionsEdt4 as text
%        str2double(get(hObject,'String')) returns contents of RepetitionsEdt4 as a double


% --- Executes during object creation, after setting all properties.
function RepetitionsEdt4_CreateFcn(hObject, eventdata, handles)
% hObject    handle to RepetitionsEdt4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function InterPulseEdt4_Callback(hObject, eventdata, handles)
% hObject    handle to InterPulseEdt4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of InterPulseEdt4 as text
%        str2double(get(hObject,'String')) returns contents of InterPulseEdt4 as a double


% --- Executes during object creation, after setting all properties.
function InterPulseEdt4_CreateFcn(hObject, eventdata, handles)
% hObject    handle to InterPulseEdt4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function PulseWidthEdt4_Callback(hObject, eventdata, handles)
% hObject    handle to PulseWidthEdt4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: getsetvaluestofig(handles)(hObject,'String') returns contents of PulseWidthEdt4 as text
%        str2double(get(hObject,'String')) returns contents of PulseWidthEdt4 as a double


% --- Executes during object creation, after setting all properties.
function PulseWidthEdt4_CreateFcn(hObject, eventdata, handles)
% hObject    handle to PulseWidthEdt4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function TriggerDelay3_Callback(hObject, eventdata, handles)
% hObject    handle to TriggerDelay3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of TriggerDelay3 as text
%        str2double(get(hObject,'String')) returns contents of TriggerDelay3 as a double


% --- Executes during object creation, after setting all properties.
function TriggerDelay3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to TriggerDelay3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function RepetitionsEdt3_Callback(hObject, eventdata, handles)
% hObject    handle to RepetitionsEdt3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of RepetitionsEdt3 as text
%        str2double(get(hObject,'String')) returns contents of RepetitionsEdt3 as a double


% --- Executes during object creation, after setting all properties.
function RepetitionsEdt3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to RepetitionsEdt3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function InterPulseEdt3_Callback(hObject, eventdata, handles)
% hObject    handle to InterPulseEdt3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of InterPulseEdt3 as text
%        str2double(get(hObject,'String')) returns contents of InterPulseEdt3 as a double


% --- Executes during object creation, after setting all properties.
function InterPulseEdt3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to InterPulseEdt3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function PulseWidthEdt3_Callback(hObject, eventdata, handles)
% hObject    handle to PulseWidthEdt3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of PulseWidthEdt3 as text
%        str2double(get(hObject,'String')) returns contents of PulseWidthEdt3 as a double


% --- Executes during object creation, after setting all properties.
function PulseWidthEdt3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to PulseWidthEdt3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function TriggerDelay2_Callback(hObject, eventdata, handles)
% hObject    handle to TriggerDelay2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of TriggerDelay2 as text
%        str2double(get(hObject,'String')) returns contents of TriggerDelay2 as a double


% --- Executes during object creation, after setting all properties.
function TriggerDelay2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to TriggerDelay2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function RepetitionsEdt2_Callback(hObject, eventdata, handles)
% hObject    handle to RepetitionsEdt2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of RepetitionsEdt2 as text
%        str2double(get(hObject,'String')) returns contents of RepetitionsEdt2 as a double


% --- Executes during object creation, after setting all properties.
function RepetitionsEdt2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to RepetitionsEdt2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function InterPulseEdt2_Callback(hObject, eventdata, handles)
% hObject    handle to InterPulseEdt2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of InterPulseEdt2 as text
%        str2double(get(hObject,'String')) returns contents of InterPulseEdt2 as a double


% --- Executes during object creation, after setting all properties.
function InterPulseEdt2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to InterPulseEdt2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function PulseWidthEdt2_Callback(hObject, eventdata, handles)
% hObject    handle to PulseWidthEdt2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
setvaluestofig(handles)
% Hints: get(hObject,'String') returns contents of PulseWidthEdt2 as text
%        str2double(get(hObject,'String')) returns contents of PulseWidthEdt2 as a double


% --- Executes during object creation, after setting all properties.
function PulseWidthEdt2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to PulseWidthEdt2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Creates and returns a handle to the GUI figure. 
function h1 = GUIStageSequence_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'text', 30, ...
    'axes', 2, ...
    'popupmenu', 2, ...
    'uipanel', 8, ...
    'edit', 29, ...
    'pushbutton', 2), ...
    'override', 0, ...
    'release', [], ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', '/home/thomas/00_Git_repos/Matlab-Arduino-RTData/private/GUIStageSequence.m', ...
    'lastFilename', '/home/thomas/00_Git_repos/Matlab-Arduino-RTData/StageSequence.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'Position',[135.8 45.6971153846154 160.857142857143 38.6875],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'CurrentAxesMode','manual',...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','StageSequence',...
'NumberTitle','off',...
'Tag','figure1',...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'ScreenPixelsPerInchMode','manual',...
'HandleVisibility','callback',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'axes1';

h2 = axes(...
'Parent',h1,...
'FontUnits',get(0,'defaultaxesFontUnits'),...
'Units','characters',...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
'PlotBoxAspectRatio',[1 0.238820171265461 0.238820171265461],...
'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
'XTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'XTickMode',get(0,'defaultaxesXTickMode'),...
'XTickLabel',{  '0'; '0.1'; '0.2'; '0.3'; '0.4'; '0.5'; '0.6'; '0.7'; '0.8'; '0.9'; '1' },...
'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
'YTick',[0 0.2 0.4 0.6 0.8 1],...
'YTickMode',get(0,'defaultaxesYTickMode'),...
'YTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
'CameraMode',get(0,'defaultaxesCameraMode'),...
'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
'XRulerMode',get(0,'defaultaxesXRulerMode'),...
'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
'YRulerMode',get(0,'defaultaxesYRulerMode'),...
'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
'Tag','axes1',...
'Position',[7 1.0625 150.142857142857 15.6875],...
'ActivePositionProperty','position',...
'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
'LooseInset',[20.9114285714286 4.255625 15.2814285714286 2.9015625],...
'LooseInsetMode',get(0,'defaultaxesLooseInsetMode'),...
'SortMethod','childorder',...
'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h3 = get(h2,'title');

set(h3,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000522207012 1.0109561752988 0.5],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','bold',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','Axes Title',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h4 = get(h2,'xlabel');

set(h4,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[0.500000476837158 -0.0942895066136542 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','top',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h5 = get(h2,'ylabel');

set(h5,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[-0.0288614012440386 0.500000476837158 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',90,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',11,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

h6 = get(h2,'zlabel');

set(h6,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[0 0 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontUnitsMode','auto',...
'FontSize',10,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','left',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','middle',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'UnitsMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','off',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto');

appdata = [];
appdata.lastValidTag = 'SelectPop';

h7 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'All Digital Controls'; 'Digital Control 1'; 'Digital Control 2'; 'Digital Control 3'; 'Digital Control 4' },...
'Style','popupmenu',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[7 17.0625 20.7142857142857 2],...
'Callback',@(hObject,eventdata)GUIStageSequence('SelectPop_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('SelectPop_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','SelectPop');

appdata = [];
appdata.lastValidTag = 'uipanel1';

h8 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Digital Control 1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','uipanel1',...
'Position',[2.28571428571429 21.25 35.8571428571429 12.5625]);

appdata = [];
appdata.lastValidTag = 'PulseWidthEdt1';

h9 = uicontrol(...
'Parent',h8,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 9.3125 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('PulseWidthEdt1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('PulseWidthEdt1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','PulseWidthEdt1');

appdata = [];
appdata.lastValidTag = 'InterPulseEdt1';

h10 = uicontrol(...
'Parent',h8,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 6.75 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('InterPulseEdt1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('InterPulseEdt1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','InterPulseEdt1',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'RepetitionsEdt1';

h11 = uicontrol(...
'Parent',h8,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 4.1875 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('RepetitionsEdt1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('RepetitionsEdt1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','RepetitionsEdt1',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'TriggerDelay1';

h12 = uicontrol(...
'Parent',h8,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 1.625 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('TriggerDelay1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('TriggerDelay1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','TriggerDelay1',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text2';

h13 = uicontrol(...
'Parent',h8,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Pulse Width',...
'Style','text',...
'Position',[1.42857142857143 8.9375 12.8571428571429 1.5625],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text2');

appdata = [];
appdata.lastValidTag = 'text3';

h14 = uicontrol(...
'Parent',h8,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Inter Pulse Period',...
'Style','text',...
'Position',[1.42857142857143 6.375 16.7142857142857 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text3');

appdata = [];
appdata.lastValidTag = 'text4';

h15 = uicontrol(...
'Parent',h8,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Pulse Repetitions',...
'Style','text',...
'Position',[1.42857142857143 3.8125 16.2857142857143 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text4');

appdata = [];
appdata.lastValidTag = 'text5';

h16 = uicontrol(...
'Parent',h8,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Trigger Delay',...
'Style','text',...
'Position',[1.42857142857143 1.1875 12.8571428571429 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text5');

appdata = [];
appdata.lastValidTag = 'DoneBttn';

h17 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Done',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[132.857142857143 35.4375 24.2857142857143 2.0625],...
'Callback',@(hObject,eventdata)GUIStageSequence('DoneBttn_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','DoneBttn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel5';

h18 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Digital Control 2',...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel5',...
'Position',[42.8571428571429 21.25 35.8571428571429 12.5625]);

appdata = [];
appdata.lastValidTag = 'text21';

h19 = uicontrol(...
'Parent',h18,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Trigger Delay',...
'Style','text',...
'Position',[1.42857142857143 1.1875 12.8571428571429 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text21');

appdata = [];
appdata.lastValidTag = 'text20';

h20 = uicontrol(...
'Parent',h18,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Pulse Repetitions',...
'Style','text',...
'Position',[1.42857142857143 3.8125 16.2857142857143 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text20');

appdata = [];
appdata.lastValidTag = 'text19';

h21 = uicontrol(...
'Parent',h18,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Inter Pulse Period',...
'Style','text',...
'Position',[1.42857142857143 6.375 16.7142857142857 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text19');

appdata = [];
appdata.lastValidTag = 'text18';

h22 = uicontrol(...
'Parent',h18,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Pulse Width',...
'Style','text',...
'Position',[1.42857142857143 8.9375 12.8571428571429 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text18');

appdata = [];
appdata.lastValidTag = 'TriggerDelay2';

h23 = uicontrol(...
'Parent',h18,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 1.625 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('TriggerDelay2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('TriggerDelay2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','TriggerDelay2',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'RepetitionsEdt2';

h24 = uicontrol(...
'Parent',h18,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 4.1875 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('RepetitionsEdt2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('RepetitionsEdt2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','RepetitionsEdt2',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'InterPulseEdt2';

h25 = uicontrol(...
'Parent',h18,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 6.75 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('InterPulseEdt2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('InterPulseEdt2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','InterPulseEdt2',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'PulseWidthEdt2';

h26 = uicontrol(...
'Parent',h18,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 9.3125 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('PulseWidthEdt2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('PulseWidthEdt2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','PulseWidthEdt2',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'uipanel6';

h27 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Digital Control 3',...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel6',...
'Position',[83.4285714285714 21.25 35.8571428571428 12.5625]);

appdata = [];
appdata.lastValidTag = 'text25';

h28 = uicontrol(...
'Parent',h27,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Trigger Delay',...
'Style','text',...
'Position',[1.42857142857143 1.1875 12.8571428571429 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text25');

appdata = [];
appdata.lastValidTag = 'text24';

h29 = uicontrol(...
'Parent',h27,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Pulse Repetitions',...
'Style','text',...
'Position',[1.42857142857143 3.8125 16.2857142857143 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text24');

appdata = [];
appdata.lastValidTag = 'text23';

h30 = uicontrol(...
'Parent',h27,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Inter Pulse Period',...
'Style','text',...
'Position',[1.42857142857143 6.375 16.7142857142857 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text23');

appdata = [];
appdata.lastValidTag = 'text22';

h31 = uicontrol(...
'Parent',h27,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Pulse Width',...
'Style','text',...
'Position',[1.42857142857143 8.9375 12.8571428571429 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text22');

appdata = [];
appdata.lastValidTag = 'TriggerDelay3';

h32 = uicontrol(...
'Parent',h27,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 1.625 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('TriggerDelay3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('TriggerDelay3_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','TriggerDelay3',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'RepetitionsEdt3';

h33 = uicontrol(...
'Parent',h27,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 4.1875 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('RepetitionsEdt3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('RepetitionsEdt3_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','RepetitionsEdt3',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'InterPulseEdt3';

h34 = uicontrol(...
'Parent',h27,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 6.75 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('InterPulseEdt3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('InterPulseEdt3_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','InterPulseEdt3',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'PulseWidthEdt3';

h35 = uicontrol(...
'Parent',h27,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 9.3125 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('PulseWidthEdt3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('PulseWidthEdt3_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','PulseWidthEdt3',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'uipanel7';

h36 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Digital Control 4',...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel7',...
'Position',[124.285714285714 21.25 35.8571428571429 12.5625]);

appdata = [];
appdata.lastValidTag = 'text29';

h37 = uicontrol(...
'Parent',h36,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Trigger Delay',...
'Style','text',...
'Position',[1.42857142857143 1.1875 12.8571428571429 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text29');

appdata = [];
appdata.lastValidTag = 'text28';

h38 = uicontrol(...
'Parent',h36,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Pulse Repetitions',...
'Style','text',...
'Position',[1.42857142857143 3.8125 16.2857142857143 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text28');

appdata = [];
appdata.lastValidTag = 'text27';

h39 = uicontrol(...
'Parent',h36,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Inter Pulse Period',...
'Style','text',...
'Position',[1.42857142857143 6.375 16.7142857142857 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text27');

appdata = [];
appdata.lastValidTag = 'text26';

h40 = uicontrol(...
'Parent',h36,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Pulse Width',...
'Style','text',...
'Position',[1.42857142857143 8.9375 12.8571428571429 1.5625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text26');

appdata = [];
appdata.lastValidTag = 'TriggerDelay4';

h41 = uicontrol(...
'Parent',h36,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 1.625 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('TriggerDelay4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('TriggerDelay4_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','TriggerDelay4',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'RepetitionsEdt4';

h42 = uicontrol(...
'Parent',h36,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 4.1875 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('RepetitionsEdt4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('RepetitionsEdt4_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','RepetitionsEdt4',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'InterPulseEdt4';

h43 = uicontrol(...
'Parent',h36,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 6.75 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('InterPulseEdt4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('InterPulseEdt4_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','InterPulseEdt4',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'PulseWidthEdt4';

h44 = uicontrol(...
'Parent',h36,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[19.1428571428571 9.3125 9.42857142857143 1.4375],...
'Callback',@(hObject,eventdata)GUIStageSequence('PulseWidthEdt4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)GUIStageSequence('PulseWidthEdt4_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','PulseWidthEdt4',...
'KeyPressFcn',blanks(0));


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % GUISTAGESEQUENCE
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % GUISTAGESEQUENCE(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % GUISTAGESEQUENCE('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % GUISTAGESEQUENCE(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


