function obj=makeLiveInterface(obj,nbFigs,TheFig)
figure(TheFig);
set(gcf, 'Position', get(0,'Screensize'))

for k=1:nbFigs
    subplot(min(nbFigs,4),ceil(nbFigs/4),k)
    obj.graphics.axes_handles(k)=gca;
    obj.graphics.plot_handles(k)=plot(1,1,'*');
    if k==1
        obj.graphics.text_handles(1)=title(sprintf('%3.2f s',toc));
    end
end

uicontrol(...
'Parent',gcf,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','normalized',...
'ListboxTop',0,...
'String','GO',...
'Position',[0.05 0.9 0.05 0.05],...
'BackgroundColor',[0.831 0.816 0.784],...
'Callback',@(hObject, eventdata)bttncallback(hObject, eventdata,obj),...
'Children',[],...
'KeyPressFcn',blanks(0),...
'ParentMode','manual',...
'ButtonDownFcn',blanks(0),...
'Tag','pushbutton1',...
'UserData',[]);
end

function bttncallback(hObject, eventdata,obj)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
obj
end
    